"use strict"

export const STATUS_DENY = "DENY"
export const STATUS_ALLOW = "ALLOW"
export const STATUS_DISMISS = "DISMISS"
export const STATUSES = [STATUS_DENY, STATUS_ALLOW, STATUS_DISMISS]

export const CATEGORY_UNCATEGORIZED = 'UNCATEGORIZED';
export const CATEGORY_ESSENTIAL = 'ESSENTIAL';
export const CATEGORY_PERSONALIZATION = 'PERSONALIZATION';
export const CATEGORY_ANALYTICS = 'ANALYTICS';
export const CATEGORY_MARKETING = 'MARKETING'

export const CATEGORIES = [CATEGORY_UNCATEGORIZED, CATEGORY_ESSENTIAL, CATEGORY_PERSONALIZATION, CATEGORY_ANALYTICS, CATEGORY_MARKETING]

export const categoriesDisplayNames = {
  [CATEGORY_UNCATEGORIZED]: "Uncategorized",
  [CATEGORY_ESSENTIAL]: "Necessary (always active)",
  [CATEGORY_PERSONALIZATION]: "Personalization",
  [CATEGORY_ANALYTICS]: "Analytics",
  [CATEGORY_MARKETING]: "Marketing"
}
