name: main

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: build package
        run: |
          npm i
          npm run build

      - name: test package
        run: |
          npm run test

  publish_package:
    needs: build_and_test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js v12.x
        uses: actions/setup-node@v1
        with:
          node-version: v12.x

      - name: build
        run: |
          npm i
          npm run build

      #- name: debug publish_package
      #  uses: actions/bin/debug@master

      - name: publish to npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release@17

